title:      'Yet Another Scheme Tutorial'
subtitle:   ''
slug:       'yast'
author:     'Takafumi Shido'
translator: 'DeathKing'
edition:    'First edition'
language:   'zh_CN'
publisher:  ''
pubdate:    ''
isbn:       ''
identifier: '' # only for epub
id_scheme:  '' # only for epub

contents:
  # available content types: acknowledgement, afterword, appendix, author,
  # blank, chapter, conclusion, cover, dedication, edition, epilogue, foreword,
  # glossary, introduction, license, lof (list of figures), lot (list of
  # tables), part, preface, prologue, title, toc (table of contents)
  - { element: cover }
  - { element: preface, number:  0, file: index.md   }
  - { element: preface, number:  1, file: preface.md }
  - { element: chapter, number:  1, file: chapter1.md }
  - { element: chapter, number:  2, file: chapter2.md }
  - { element: chapter, number:  3, file: chapter3.md }
  - { element: chapter, number:  4, file: chapter4.md }
  - { element: chapter, number:  5, file: chapter5.md }
  - { element: chapter, number:  6, file: chapter6.md }
  - { element: chapter, number:  7, file: chapter7.md }
  - { element: chapter, number:  8, file: chapter8.md }
  - { element: chapter, number:  9, file: chapter9.md }
  - { element: chapter, number: 10, file: chapter10.md }
  - { element: chapter, number: 11, file: chapter11.md }
  - { element: chapter, number: 12, file: chapter12.md }
  - { element: chapter, number: 13, file: chapter13.md }
  - { element: chapter, number: 14, file: chapter14.md }
  - { element: chapter, number: 15, file: chapter15.md }

formats:
  pdf:
    label:
      deep:     3
      elements: ['appendix', 'chapter', 'part'] # labels also available for: "figure", "table", "codeblock"
    toc:
      deep:     2
      elements: ['appendix', 'chapter', 'part']

  site:
    label:
      deep:     3
      elements: ['toc', 'preface', 'chapter'] # labels also available for: "figure", "table", "codeblock"
    toc:
      deep:     2 # toc in single page
      elements: ['appendix', 'chapter']

  epub:
    label:
      deep:     3
      elements: ['appendix', 'chapter', 'part'] # labels also available for: "figure", "table", "codeblock"
    toc:
      deep:     1
      elements: ['appendix', 'chapter', 'part']

  mobi:
    label:
      deep:     3
      elements: ['appendix', 'chapter', 'part'] # labels also available for: "figure", "table", "codeblock"
    toc:
      deep:     1
      elements: ['appendix', 'chapter', 'part']
